name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compiler-dev-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compiler-Dev-Style-Check 
      run:  python3 ./scripts/lint.py  --recursive ./compiler/dev
  compiler-test-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compiler-Test-Style-Check
      run:  python3 ./scripts/lint.py  --recursive ./compiler/test

  build-compiler:
    runs-on: ubuntu-latest
    needs: [compiler-dev-style-checking, compiler-test-style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Compiler Building
      run: echo $GITHUB_ACTION_PATH
    - name: Building Compiler
      run: sh ./scripts/github/buildCompiler.sh
    - name: Upload objects artifact
      uses: actions/upload-artifact@v2
      with:
        name: objects-artifact
        path: ./compiler/build

#   test:
#     runs-on: ubuntu-latest
#     needs: [compiler-dev-style-checking, compiler-test-style-checking, build-compiler]
#     steps:
#     - uses: actions/checkout@v3
#     - name: Configure gtest
#       run: sh /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/tools/github/configure-test.sh
#     - name: Building tests
#       run: make -C tests build-unittests
#     - name: Running tests
#       run: make -C tests run-unittests