name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compiler-dev-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compiler-Dev-Style-Check 
      run:  python3 ./scripts/lint.py  --recursive ./compiler/dev
  compiler-test-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compiler-Test-Style-Check
      run:  python3 ./scripts/lint.py  --recursive ./compiler/tests

  build-compiler:
    runs-on: ubuntu-latest
    needs: [compiler-dev-style-checking, compiler-test-style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Compiler Building
      run: sh ${{ github.workspace }}/scripts/github/confgiureBuild.sh
    - name: Building Compiler
      run: sh ${{ github.workspace }}/scripts/github/buildCompiler.sh
    - name: Upload objects artifact
      uses: actions/upload-artifact@v2
      with:
        name: objects-artifact
        path: ${{ github.workspace }}/compiler/build

  unit-tests:
    runs-on: ubuntu-latest
    needs: [compiler-dev-style-checking, compiler-test-style-checking, build-compiler]
    steps:
    - uses: actions/checkout@v3
    - name: Configuring Tests
      run:  sh ${{ github.workspace }}/scripts/github/configureUnitTests.sh
    - name: Building Tests
      run:  sh ${{ github.workspace }}/scripts/github/buildTests.sh
    - name: Running tests
      run:  sh ${{ github.workspace }}/scripts/github/runUnitTests.sh

  regression-tests:
    runs-on: ubuntu-latest
    needs: [compiler-dev-style-checking, compiler-test-style-checking, build-compiler]
    steps:
    - uses: actions/checkout@v3
    - name: Configuring Tests
      run:  sh ${{ github.workspace }}/scripts/github/configureRegressionTests.sh
    - name: Download objects artifact
      uses: actions/download-artifact@v2
      with:
        name: objects-artifact
        path: ${{ github.workspace }}/compiler/build/
    - name: Converting to executable
      run: chmod +x ${{ github.workspace }}/compiler/build/cbit && ls -l ${{ github.workspace }}/compiler/build/
    - name: Running tests
      run:  sh ${{ github.workspace }}/scripts/github/runRegressionTests.sh